have_fun: true

code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  locale: ko-KR
  translation_mode: auto
  max_review_comments: -1
  pull_request_opened:
    help: false
    summary: true
    code_review: true
  custom_rules:
      enable: true
