name: backend-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
    paths:
      - "backend/**"

jobs:
  build:
    strategy:
      matrix:
        java-distribution: ['temurin']
        java-version: ['21, 23']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.java-distribution }}
          java-version: ${{ matrix.java-version }}
          cache: 'gradle'
      - name: Run build
        run: ./gradlew build --no-daemon
      - name: Run test
        run: ./gradlew test
